import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { inventory } from "@/data/inventory";

export default function Home() {
  const questions = inventory.question;
  const question = (obj = 1) => {
    return questions[`question_${obj}`][`question`];
  }
  console.log(question(1));

  // const getDate = (obj, keyName) => {
  //   var results;
  //   for (let key in obj){  
  //     results = `<p>${obj[key][keyName]}</p>`;
  //   }
  //   return results;
  // }
  // const question = getDate(questions, 'question_1');
  // console.log(question);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div id="question"></div>
      </main>
    </>
  );
}
