import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Quiz from "@/components/Quiz";
import Results from "@/components/Results";

export default function Home() {
  const [showQuiz, setShowQuiz] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [finalAnswers, setFinalAnswers] = useState({});

  const handleResetSession = () => {
    sessionStorage.removeItem('sessionData');
    //console.log('Session data reset successfully.');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <button onClick={() => {setShowQuiz(true); setShowResult(false);}}>Start Quiz</button>
        <button onClick={() => handleResetSession()}>Reset Quiz</button>
        {(showQuiz && !showResult) && (<><Quiz setShowResult={setShowResult} setFinalAnswers={setFinalAnswers} /></>)}
        {showResult && (<><Results finalAnswers={finalAnswers} /></>)}
      </main>
    </>
  );
}
