import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { inventory } from "@/data/inventory";

export default function Home() {
  // console.log(inventory);
  const questions = inventory.question;
  console.log(questions);
  /*
  for (let key in questions){
    let question = questions_[key].question;
    console.log(question);
  }
  */

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>

      </main>
    </>
  );
}
