import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { inventory } from "@/data/inventory";
import Question from "@/components/Question";
import Script from 'next/script'

export default function Home() {
  // const questions = inventory.question;
  // const question = (obj) => {
  //   return questions[`question_${obj}`][`question`];
  // }
  // const Form = `<p>html content</p>`;


  // console.log(question(2));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        {/* <div id="question"><li>{question(1)}</li></div>
        <div dangerouslySetInnerHTML={{
        __html: `Form`}} /> */}
        <Question></Question>
      </main>
    </>
  );
}
